import canonical_forms_reductions_classification_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace canonical_forms_reductions_classification_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end canonical_forms_reductions_classification_theorem_canonical_lane_mathlib
end HautevilleHouse
